# Spend - Boost

In [2]:
#//----------------------------
#//LIBRARIES
    #Math
import math
    #Numeric Python
import numpy as np
    #Pandas (dataframes)
import pandas as pd
    #datetime for fate manipulation
from datetime import datetime, timedelta 
    #Regex for advanced string matching
import re
    #for time related stuff
import time
    #json library
import json
    #Analyst tools
import sys
sys.path.append('../')
from analysts_tools.growth import *
    #Procurement tools
from procurement_lib import send_slack_notification

In [257]:
#//---------------------------------------------------------------------------------------------------------------------------
#// Paraemtros
city_code = 'MDE'
todays_date = '2022-05-03' 
non_buyers_date = '2022-04-03'
customer_date_desde = '2022-02-03'
    #data for sku sales data
sku_date_desde = '2022-03-03'

In [258]:
#//--------------------------------------
#//Ruta de data
#segmentos_prev2 = pd.read_csv('import_data/segments/Segments_W7.csv') 

segmentos_full = pd.read_csv('import_data/segments/Segments_W18.csv') 
segmentos_full = segmentos_full.rename(columns={"Microsegment": "microsegment"})

In [259]:
#//KAMs customers
users_eliminar_kam = pd.read_csv("import_data/segments/KAMs_MAY.csv", sep=',')["customer_id"].unique().tolist()

In [260]:
#//Users to ignore
users_eliminar = users_eliminar_kam #+ segmentos_prev2['customer_id'].unique().tolist()

In [261]:
#//Clean segment_names
segmentos_full['microsegment'] = segmentos_full['microsegment'].str.replace('s/café da manhã','')
segmentos_full['microsegment'] = segmentos_full['microsegment'].str.replace('c/café da manhã','')
segmentos_full['microsegment'] = segmentos_full['microsegment'].str.replace('c/desayuno','')
segmentos_full['microsegment'] = segmentos_full['microsegment'].str.replace('s/desayuno','')
segmentos_full['microsegment'] = segmentos_full['microsegment'].str.strip()
segmentos_full['microsegment'] = segmentos_full['microsegment'].apply(lambda x: 'Taquería' if 'Taquería' in x else x)
segmentos_full['microsegment'] = segmentos_full['microsegment'].apply(lambda x: x.replace('Empanadas/Arepas','Empanadas/arepas'))
segmentos_full['microsegment'] = segmentos_full['microsegment'].apply(lambda x: x.replace('Parrilla/Asadero','Parrilla/asadero'))

#forced_skus['microsegment'] = forced_skus['microsegment'].str.strip()
#forced_skus['microsegment'] = forced_skus['microsegment'].str.replace('Comida saludable/Juguerías','Juguería/Comida saludable')

In [262]:
def detectSKUs(skus, strs):
    
    if  str(strs)=='nan':
        return True #To exclude nans    
    for sku in skus:
        if str(sku) in strs:
            return True
    return False

In [263]:
#//Remove skus 
skus_remove = [
271395,
271396,
271392,
99017,
324145,
324143,
56606,
56612,
-301818, #Diana
124661, #Diana
124659, #Diana
56612, #alquería
401540, #alquería 
56606, #alquería
90176, #alquería
266755, #alquería
126505, #alquería
#### experimento mayo
-303030,
124708,
124710,
-303057,
124702,
124700,
124716,
63697,
280865,
280868,
280862,
440367,
-304254,
-302913,
277542,
-300543,
62912,
212438,
-302130,
210161,
210159,
97137,
83969,
241989,
271594,
271602,
99017,
147339,
254113,
254112,
31507,
82996,
102355,
111139,
118025,
118027,
118020,
-304413,
48733,
-302271,
-302286,
367833,
136080,
136082,
130690,
290511,
169189,
290224,
290223,
290222,
377870,
377869,
377868,
219702,
37211,
219697,
37188,
296040,
296041,
91360,
91356,
106890,
106889,
106895,
162844,
162845,
162843,
278268,
322342,
278267,
285339,
285338,
195864,
195961,
195960,
290048,
290049,
290047,
218839,
218840,
218841,
197104,
197105,
359613,
196789,
196790,
196791,
250239,
250240,
197116,
342968,
342969,
342967,
197114,
197113,
197718,
197719,
197720,
195993,
195992,
195994,
304504,
249435,
249433,
249434,
290283,
371569,
371567,
371571,
371573,
254974,
254842,
254971,
254844,
254865,
254856,
295085,
254973,
336632,
249954,
249953,
249993,
249992,
404804,
404799
]

In [264]:
data_ventas = data_ventas_query(ciudad=city_code, tipo_cambio=1, desde=customer_date_desde, hasta = todays_date, tipo_negocio=1)

In [265]:
data_ventas = data_ventas[~data_ventas['sku_id'].isin(skus_remove)]
#forced_skus = forced_skus[~forced_skus['sku_ids'].apply(lambda x: detectSKUs(skus_remove, x))]

In [266]:
#//customers for offers
microsegmentacion_df = segmentos_full[(~segmentos_full['customer_id'].isin(users_eliminar))]

In [267]:
Data_full = data_ventas.merge(microsegmentacion_df[['customer_id','microsegment']], how = 'left', on = 'customer_id')

In [268]:
Data_full['microsegment'] = Data_full['microsegment'].fillna('Other')

In [269]:
Data_full.customer_id.nunique()

2167

In [270]:
Data_full[['customer_id','microsegment']].groupby(['microsegment']).nunique()

                                customer_id
microsegment
Comida especializada                      1
Comida rápida                             2
Corrientazo                               4
Other                                  2154
Panadería/Pastelería                      4
Panadería/Pastelería/Cafetería            1
Parrilla/asadero                          1

In [271]:
Data_full.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 68944 entries, 0 to 68943
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   submit_date        68944 non-null  datetime64[ns]
 1   close_date         68944 non-null  datetime64[ns]
 2   month              68944 non-null  object
 3   order_id           68944 non-null  int64
 4   order_item_id      68944 non-null  int64
 5   tracking_code      68944 non-null  object
 6   customer_id        68944 non-null  int64
 7   email_address      68944 non-null  object
 8   name               68944 non-null  object
 9   gmv_usd            68944 non-null  float64
 10  discount_applied   68944 non-null  object
 11  cant               68944 non-null  float64
 12  unidades           68944 non-null  object
 13  sku_id             68944 non-null  int64
 14  padre_sku_id       68944 non-null  int64
 15  region_code        68944 non-null  object
 16  category           68944 non-null  object
 17  subcat             68944 non-null  object
 18  adjustment_reason  66653 non-null  object
 19  microsegment       68944 non-null  object
dtypes: datetime64[ns](2), float64(2), int64(5), object(11)
memory usage: 11.0+ MB

In [272]:
Data_full.category.unique()

array(['Frutas & Verduras', 'Bebidas', 'Lácteos & Huevos', 'Abarrotes',
       'Desechables', 'Aseo e Higiene'], dtype=object)

In [273]:
Data_full.subcat.unique()

array(['Verduras', 'Frutas', 'Bebidas Sin Alcohol', 'Tubérculos',
       'Huevos', 'Azúcar & Endulzantes', 'Aceites & Grasas', 'Arroz',
       'Contenedores', 'Papel & Toallas', 'Granos',
       'Detergente, Jabón & Lavalozas', 'Desinfectantes & Sanitizantes',
       'Pasta', 'Vasos', 'Harinas & Mezclas',
       'Café, Chocolate e Infusiones', 'Leches', 'Cremas',
       'Cubiertos & Pitillos', 'Derivados Lácteos', 'Sal & Sazonadores',
       'Platos & Bandejas', 'Empaque & Envoltura',
       'Panadería & Repostería', 'Bolsas'], dtype=object)

In [276]:
Data_full[['category','subcat']].loc[Data_full.category.isin(['Frutas & Verduras', 'Bebidas'])].subcat.unique()

array(['Verduras', 'Frutas', 'Bebidas Sin Alcohol', 'Tubérculos'],
      dtype=object)

In [275]:
Data_full.microsegment.unique()

array(['Other', 'Comida rápida', 'Panadería/Pastelería', 'Corrientazo',
       'Parrilla/asadero', 'Comida especializada',
       'Panadería/Pastelería/Cafetería'], dtype=object)

In [222]:
#//---------------------------------------------------
#//Dictionaries -> Segments per city y subcats/aproach per city

In [277]:
Segment_by_City= {'BOG':['Other', 'Corrientazo', 'Empanadas/arepas', 'Panadería/Pastelería',
                           'Comida rápida', 'Cafetería', 'Comida especializada',
                           'Parrilla/asadero'],
               
              'BAQ': ['Other', 'Comida rápida', 'Corrientazo',
                       'Comida de mar y Colombiana', 'Panadería/Pastelería/Cafetería',
                       'Fritos'],
               
              'CMX':['Other', 'Fonda',
                       'Juguería/Comida saludable', 'Taquería',
                       'Comida rápida', 'Comida especializada'],
               
              'GDL':['Other'],
                
              'BHZ':['Other'],
            
              'CWB':['Other'],
            
              'MDE':['Other'],
               
              'SPO':['Comida brasileira y saudavel', 'Prato do dia', 'Other',
                       'Comida internacional/Grill', 'Lanches', 'Comida por quilo',
                       'Padaria/Cafeteria/Bolos', 'Pizza/Comida Italiana', 'Sucos/Açaí']
                 }

In [278]:
####BMS########### columna R

Subcats_by_Type = {
    
              'BOG': {'BMS':['Verduras', 'Tubérculos', 'Frutas', 'Cerdo', 'Contenedores','Res'], 
                      'All':['Embutidos']} ,
               
              'BAQ': {'BMS':['Tubérculos', 'Verduras', 'Frutas'], 
                      'All':[]},
    
              'GDL':{'BMS':[], 
                     'All':['Frutas', 'Tubérculos', 'Verduras', 'Cerdo', 'Res', 'Pollo',
                           'Embutidos', 'Refrescos', 'Jugos', 'Pescados & Mariscos']},
               
              'CMX':{'BMS':['Frutas', 'Verduras', 'Tubérculos'], 
                     'All':[]},
    
              'MDE':{'BMS':[], 
                     'All':['Verduras', 'Frutas', 'Bebidas Sin Alcohol', 'Tubérculos']},
    
              'CWB':{'BMS':[], 
                     'All':['Verduras', 'Tubérculos', 'Legumes', 'Frutas', 'Refrigerante',
                               'Cerveja', 'Água', 'Suco', 'Hortaliças', 'Frango', 'Suínos',
                               'Carne Vermelha', 'Embutidos', 'Peixes e Frutos do Mar']},
               
              'BHZ':{'BMS':[], 
                     'All':['Verduras', 'Tubérculos', 'Legumes', 'Frutas', 'Refrigerante',
                           'Cerveja', 'Água', 'Suco', 'Hortaliças', 'Frango', 'Suínos',
                           'Carne Vermelha', 'Embutidos', 'Peixes e Frutos do Mar']},
               
              'SPO':{'BMS':['Frutas', 'Verduras', 'Legumes', 'Tubérculos','Queijos'], 
                     'All':[]}}

In [279]:
#### ALL ###########
Subcats_by_Segment = {
    "BAQ":{
        'Other': ['Frutas','Verduras','Tubérculos'],
        
        "Corrientazo":['Verduras','Tubérculos'],
        
        'Comida de mar y Colombiana':['Frutas','Verduras'],
        
        "Comida rápida":['Verduras','Tubérculos'],
        
        "Fritos":['Tubérculos'],
        
        "Panadería/Pastelería/Cafetería":['Frutas','Verduras'], 
                        
        'Parrilla/asadero':[],
        
        'Comida especializada':[],
        
        'Tienda/Restaurante':[]   
        
    },

    "BOG":{
        "Corrientazo":['Verduras','Tubérculos','Contenedores','Res','Cerdo'], 
        
        'Panadería/Pastelería':['Frutas','Contenedores'],
        
        'Comida rápida':['Verduras','Tubérculos','Contenedores','Embutidos'],
        
        'Empanadas/arepas':['Tubérculos'],
        
        'Parrilla/asadero':['Res','Cerdo','Embutidos'],
                                    
        'Comida especializada':['Verduras','Contenedores','Res','Cerdo'],
        
        'Cafetería':['Frutas','Verduras','Contenedores'], 
        
        'Other' :['Frutas','Verduras','Tubérculos','Contenedores']
    },
    
    #'Granos', 'Azúcar & Endulzantes', 'Pasta', 'Arroz',
      # 'Aceites & Grasas', 'Sal & Sazonadores',
       #'Café, Chocolate e Infusiones', 'Harinas & Mezclas', 'Salsas',
       #'Panadería & Repostería', 'Enlatados', 'Otros Abarrotes',
       #'Panadería & Tortilleria', 'Chiles Secos',
       #'Mermeladas y Confituras'
    
    'CMX':{
        'Fonda':['Frutas','Verduras','Tubérculos'],
        
        'Taquería':['Frutas','Verduras'],
        
        'Juguería/Comida saludable':['Frutas','Verduras'],
        
        'Panadería/Pastelería':[], 
        
        'Comida rápida':['Verduras','Tubérculos'], 
        
        'Comida especializada':['Frutas','Verduras'],              
      
        'Cafetería':[],
        
        'Other':['Frutas','Verduras','Tubérculos'] 
    },
    
    'GDL':{
        'Other':['Frutas', 'Tubérculos', 'Verduras', 'Cerdo', 'Res', 'Pollo',
                   'Embutidos', 'Refrescos', 'Jugos', 'Pescados & Mariscos']                   
    },

    'MDE':{
        'Other':['Verduras', 'Frutas', 'Bebidas Sin Alcohol', 'Tubérculos']                   
    },
    
    'CWB':{
        'Other':['Verduras', 'Tubérculos', 'Legumes', 'Frutas', 'Refrigerante',
                   'Cerveja', 'Água', 'Suco', 'Hortaliças', 'Frango', 'Suínos',
                   'Carne Vermelha', 'Embutidos', 'Peixes e Frutos do Mar']                   
    },
    
    'BHZ':{
        'Other':['Verduras', 'Tubérculos', 'Legumes', 'Frutas', 'Refrigerante',
                   'Cerveja', 'Água', 'Suco', 'Hortaliças', 'Frango', 'Suínos',
                   'Carne Vermelha', 'Embutidos', 'Peixes e Frutos do Mar']                  
    },
    
    'SPO':{
        
        'Other' : ['Frutas','Verduras','Legumes','Tubérculos'],
        
        'Prato do dia': ['Verduras','Legumes','Tubérculos'],
        
        'Comida por quilo' : ['Verduras','Legumes','Tubérculos','Queijos'],
        
        'Lanches':['Verduras','Legumes','Tubérculos','Queijos'],                            

        'Padaria/Cafeteria/Bolos':['Queijos'],
        
        'Comida brasileira y saudavel': ['Frutas','Verduras','Legumes','Tubérculos','Queijos'],
        
        'Comida internacional/Grill': ['Verduras','Legumes','Tubérculos','Queijos'],
        
        'Pizza/Comida Italiana':['Verduras','Legumes','Queijos'],
        
        'Sucos/Açaí':['Frutas']
    }
}

In [280]:
def normalize_text(raw_text):
    """
    Removes common accent characters and normalize text.
    """
    raw_text = raw_text.replace(" ", "")
    raw_text = raw_text.replace("�", "")
    raw_text = raw_text.replace("/", "")
    raw_text = re.sub(r'\s*', '', raw_text)
    raw_text = re.sub(r"[àáâãäå]", 'a', raw_text)
    raw_text = re.sub(r"[èéêë]", 'e', raw_text)
    raw_text = re.sub(r"[ìíîï]", 'i', raw_text)
    raw_text = re.sub(r"[òóôõö]", 'o', raw_text)
    raw_text = re.sub(r"[ùúûü]", 'u', raw_text)
    raw_text = re.sub(r"[ýÿ]", 'y', raw_text)
    raw_text = re.sub(r"[ß]", 'ss', raw_text)
    raw_text = re.sub(r"[ñ]", 'n', raw_text)
    raw_text = re.sub(r"[ç]", 'c', raw_text)
    raw_text = raw_text.lower()
    return raw_text

In [281]:
global_offer_csv = pd.DataFrame()
global_segment_list = [] #//for procesing


#//----------------------------------------------------------------------------
#//Big loop for creating each city segments/offers files
for microsegment in Segment_by_City[city_code]:
    print('//-------------------------------------------------------------------------------')
    print(microsegment)
    
    
    customers_ms = Data_full[(Data_full['microsegment'] == microsegment) & (~Data_full['customer_id'].isin(users_eliminar))]['customer_id'].unique()
        #//Customers para skus
    customers_for_skus_ms =  Data_full[(Data_full['microsegment'] == microsegment)]['customer_id'].unique()

    data_buyers = Data_full[Data_full['customer_id'].isin(customers_ms)]
    print(data_buyers.customer_id.nunique())
    
    #//Customers para skus
    data_skus = Data_full[Data_full['customer_id'].isin(customers_for_skus_ms)]   
    top_df = analizar_top_productos(Data_full[Data_full['customer_id'].isin(customers_for_skus_ms)])
    
#//----------------------------------------------------------------------------
#//BMS section
    subcatsxoffer = list(set(Subcats_by_Segment[city_code][microsegment])& set(Subcats_by_Type[city_code]['BMS'])) 
    print('BMS Subcats:')
    print(subcatsxoffer)   
          
    ms_name = normalize_text(microsegment) #+ '_Spend-BMS'
    #//----------------------------------------------------------------------------------------------------------------------------
    #// Separation of types of sales (non_buyers/skus for offers)

    
    a, b, c = proceso_para_csv(data_ventas=data_buyers, todays_date=todays_date, 
                non_buyers_date=non_buyers_date, city=city_code, list_to_filter=subcatsxoffer, level='subcat', additional_words=ms_name,
                          tipo ='buyers_below_median_gmv', limite=0.75, data_ventas_skus = data_skus) 
    
    #//appending to global data frame
    global_offer_csv = global_offer_csv.append(a)
    print(b.nunique())
    
    
    #c.to_csv(f'export_data/MS/nb_email_{city_code}_{ms_name}.csv', index=False)
    #//Data formating 'all_buyers'
    lst = []
    for seg in b.columns:
        id_list = b[seg].dropna().astype(int)
        d = {'name':seg, 'customersIds': list(id_list)}
        lst.append(d)     
        #//appending to global list    
        global_segment_list.append(d)
    
#//----------------------------------------------------------------------------
#//All section

    subcatsxoffer = list(set(Subcats_by_Segment[city_code][microsegment]) & set(Subcats_by_Type[city_code]['All'])) 
    print('All(Open) Subcats:')
    print(subcatsxoffer) 
    
    ms_name = normalize_text(microsegment) #+ '_Spend-All'
    #//----------------------------------------------------------------------------------------------------------------------------
    #// Separation of types of sales (non_buyers/skus for offers)

    
    a, b, c = proceso_para_csv(data_ventas=data_buyers, todays_date=todays_date, 
                non_buyers_date=non_buyers_date, city=city_code, list_to_filter=subcatsxoffer, level='subcat', additional_words=ms_name,
                          tipo ='all_buyers', limite=0.75, data_ventas_skus = data_skus) 
    
    #//appending to global data frame
    global_offer_csv = global_offer_csv.append(a)
    print(b.nunique())
    
    
    #c.to_csv(f'export_data/MS/nb_email_{city_code}_{ms_name}.csv', index=False)
    #//Data formating 'all_buyers'
    lst = []
    for seg in b.columns:
        id_list = b[seg].dropna().astype(int)
        d = {'name':seg, 'customersIds': list(id_list)}
        lst.append(d)     
        #//appending to global list    
        global_segment_list.append(d)

//-------------------------------------------------------------------------------
Other
2150
BMS Subcats:
[]
Uso de data externa
Series([], dtype: float64)
All(Open) Subcats:
['Frutas', 'Tubérculos', 'Bebidas Sin Alcohol', 'Verduras']
Uso de data externa
20220503_MDE_other_Spend-All_frutas_W18               1339
20220503_MDE_other_Spend-All_tuberculos_W18           1226
20220503_MDE_other_Spend-All_bebidassinalcohol_W18    1095
20220503_MDE_other_Spend-All_verduras_W18             1510
dtype: int64

In [282]:
global_offer_csv.to_csv(f'export_data/spend/csv_{city_code}_Spend.csv', index = False)

with open(f'export_data/spend/nb_{city_code}_Spend.txt', 'w') as outfile:
        json.dump(global_segment_list, outfile)    
with open(f'export_data/spend/nb_{city_code}_Spend.json', 'w') as outfile:
        json.dump(global_segment_list, outfile)
print(f'Done {city_code}')

Done MDE

In [283]:
global_offer_csv

,offer_name,offer_description,discount,automatically_consider_offer,start_date,end_date,max_uses_per_order,max_uses_per_customer,customer_segment_id,sku_id
0,20220503_MDE_other_Spend-All_frutas_W18,None,-1.0,true,03-05-2022,10-05-2022,-1.0,-1.0,None,363451#399049#363441#363530#363510
1,20220503_MDE_other_Spend-All_tuberculos_W18,None,-1.0,true,03-05-2022,10-05-2022,-1.0,-1.0,None,375344#420019#420017#423783#363493#363489
2,20220503_MDE_other_Spend-All_bebidassinalcohol...,None,-1.0,true,03-05-2022,10-05-2022,-1.0,-1.0,None,367471#367466#367462#367461#367459#367478#3674...
3,20220503_MDE_other_Spend-All_verduras_W18,None,-1.0,true,03-05-2022,10-05-2022,-1.0,-1.0,None,363439#363480#363443#462257#363523#363517#3634...